name: Create ServiceNow Change

on:
  push:
    branches: [ main ]
    paths:
      - '.github/actions/snow-create-change/**'
      - '.github/workflows/create-snow-change.yml'
  workflow_dispatch:
    inputs:
      description:
        description: 'Change description'
        required: true
        default: 'Automated change created from GitHub Actions'

jobs:
  create-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create ServiceNow Change
        id: create_change
        uses: ./.github/actions/snow-create-change
        with:
          username: ${{ secrets.SN_USERNAME }}
          password: ${{ secrets.SN_PASSWORD }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          template_id: ${{ secrets.TEMPLATE_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Display Access Token
        if: steps.create_change.outputs.access_token
        run: |
          echo "Access token obtained successfully"
          echo "Token: ${{ steps.create_change.outputs.access_token }}"
          
      - name: Handle Failure
        if: failure()
        run: |
          echo "Action failed. Check the logs above for details."
          exit 1
