name: 'ServiceNow Create Standard Change'
description: 'Create a standard IT change in ServiceNow using the nnash API'

inputs:
  instance:
    description: 'ServiceNow instance URL (e.g., novonordisktraining.service-now.com)'
    required: true
  username:
    description: 'ServiceNow username'
    required: true
  password:
    description: 'ServiceNow password or API token'
    required: true
  template_id:
    description: 'Template ID for the standard change'
    required: true
  description:
    description: 'Change description'
    required: true
    default: 'Automated change created from GitHub Actions'

runs:
  using: 'composite'
  steps:
    - name: Create ServiceNow Change
      shell: bash
      run: |
        # Set variables
        INSTANCE="${{ inputs.instance }}"
        USERNAME="Trunque-API"
        PASSWORD="wfasdfasd"
        DESCRIPTION="Test description"

        # Create the change request
        echo "Creating standard change request..."
        RESPONSE=$(curl -sS \
          -u "$USERNAME:$PASSWORD" \
          -X POST \
          -H "Content-Type: application/json" \
          -H "Accept: application/json" \
          -d '{
            "u_service_offering": "Platform Engineering",
            "start_date": "2025-10-12 00:00:00",
            "end_date": "2025-10-13 00:00:00",
            "work_start": "2025-10-15 00:00:00",
            "work_end": "2025-10-19 00:00:00",
            "risk": "1",
            "requested_by": "AAQG",
            "impact": "2",
            "urgency": "3",
            "implementation_plan": "Test implementation plan for the change",
            "risk_impact_analysis": "Test risk impact analysis for the change",
            "backout_plan": "Test backout plan in case of failure",
            "test_plan": "Test plan for the change",
            "cmdb_ci": "123456789asdfghjkl",
            "u_sarbox": "yes",
            "u_criticality": "other_regulatory",
            "parent": "INC4215160asdfghjkl",
            "u_release": "1dff7bc73b8e96d4cbad6d6eb5e45a80",
            "u_service_request": "RITM0781791asdfghjkl",
            "u_integration_task": "INTG0634241asdfghjkl",
            "u_change_manager": "AAQG",
            "assigned_to": "AAQG",
            "description": "'"$DESCRIPTION"'"
          }' \
          "https://$INSTANCE/api/nnash/v1/change_request/standard/create")
        
        # Check for errors
        if ! echo "$RESPONSE" | jq -e '.result' > /dev/null; then
          echo "Error creating change:"
          echo "$RESPONSE" | jq .
          exit 1
        fi
        
        # Extract and output results
        CHANGE_NUMBER=$(echo "$RESPONSE" | jq -r '.result.number')
        SYS_ID=$(echo "$RESPONSE" | jq -r '.result.sys_id')
        LINK="https://$INSTANCE/nav_to.do?uri=change_request.do?sys_id=$SYS_ID"
        
        echo "✅ Change $CHANGE_NUMBER created successfully!"
        echo "🔗 View change: $LINK"
        
        # Set outputs
        echo "change_number=$CHANGE_NUMBER" >> $GITHUB_OUTPUT
        echo "sys_id=$SYS_ID" >> $GITHUB_OUTPUT
        echo "link=$LINK" >> $GITHUB_OUTPUT
